include:
  - path: core/docker-compose.yml
    env_file: .env
  - path: orchestrator/docker-compose.yml
    env_file: .env
  - path: ai-services/docker-compose.yml
    env_file: .env
  - path: extension/docker-compose.yml
    env_file: .env
